package com.inventory.middle.domain.common.constants;

import lombok.Getter;

@Getter
public enum ResponseCodeEnum {
    SUCCESS("0", "成功"),
    FAILED("1", "失败"),
    DATA_NOT_EXISTS("3", "数据不存在"),
    SYSTEM_ERROR("99", "系统异常"),
    REPEAT_REQUEST("97", "重复请求"),
    WAIT_IN_LINE("996", "等待其他用户操作完成"),
    PARAM_IS_NULL("997", "请求参数为空"),
    REMOTE_SERVICE_FAILED("998", "远程服务调用异常"),
    PARAM_VALID_ERROR("999", "请求参数错误"),

    WAREHOUSE_NANME_EXIST("10001", "物理仓库名称已经存在"),
    WAREHOUSE_NOT_EXIST("10002", "物理仓库不存在"),
    LOGICAL_PLANT_NOT_EXIST("10003", "逻辑仓库不存在"),
    STORAGE_LOCATION_NOT_EXIST("10004", "存储地点不存在"),
    LOGICAL_PLANT_NANME_EXIST("10005", "逻辑仓库名称已经存在"),
    STORAGE_LOCATION_NANME_EXIST("10006", "存储地点名称已经存在"),
    SPECIAL_STORAGE_LOCATION_EXIST("10007", "该特殊类型存储地点已经存在"),

    /**
     * errorCode : 20001 ~ 29999 预警规则使用
     */
    LOGICAL_PLANT_MATERIAL_EXISTS("20001", "预警规则中已经存在有效的该逻辑仓的预警维度"),
    ASSIGN_MATERIAL_EXISTS("20002", "预警规则中已经存在有效的该物料的预警维度"),
    MONITOR_RULE_CREATE_FAILED("20003", "预警规则创建失败"),
    MONITOR_RULE_UPDATE_FAILED("20004", "预警规则更新失败"),
    MONITOR_RULE_DELETE_FAILED("20005", "预警规则删除失败"),
    MONITOR_MATERIAL_REPEATED("20006", "预警数据重复"),
    MONITOR_MATERIAL_EXISTS("20007", " 预警规则中已存在该物料"),
    MONITOR_NOT_EXISTS("20008", "预警规则不存在"),
    MONITOR_RULE_LINE_CREATE_FAILED("20009", "预警规则行创建失败"),
    MONITOR_RULE_LINE_UPDATE_FAILED("20010", "预警规则行保存失败"),
    MONITOR_RULE_LINE_IS_NULL("20011", "预警规则行ID为空"),
    MONITOR_SEND_MODE_ERROR("20012", "预警发送方式错误"),
    MONITOR_EMAIL_IS_NULL("20013", "预警发送邮箱为空"),
    MONITOR_EMAIL_ERROR("20014", "预警发送邮箱格式错误"),
    MONITOR_TYPE_ERROR("20015", "预警类型错误"),
    MONITOR_ENABLE_STATUS_ERROR("20016", "预警规则启停用状态错误"),
    MONITOR_DIMENSION_ERROR("20017", "预警维度错误"),
    MONITOR_LOGICAL_PLANT_IS_NULL("20018", "预警规则逻辑仓为空"),
    MONITOR_CEIL_FLOOR_IS_NULL("20019", "上限和下限不能同时为空"),
    MONITOR_CEIL_ERROR("20020", "上限必须大于0"),
    MONITOR_FLOOR_ERROR("20021", "下限必须大于等于0"),
    MONITOR_CEIL_FLOOR_ERROR("20022", "上限必须要大于下限"),
    MONITOR_LOGICAL_PLANT_EXISTS("20023", "该逻辑仓已有有效的预警规则"),
    MONITOR_MATERIAL_LOGICAL_PLANT_EXISTS("20024", "新增的物料或者逻辑仓已有有效的预警规则"),
    MONITOR_ENABLE_FAILED_RULE_LINE("20025", "预警规则无有效的预警行信息，不能启用规则"),
    MONITOR_DIMENSION_UNIQUE_ERROR("20026", "预警规则行只能使用一种预警维度"),
    MONITOR_RULE_UPDATE_FAILED_WITH_REASON("20027", "预警规则更新失败，%s已有有效的预警规则"),
    MONITOR_RULE_ALERT_CREATE_FAILED("20028", "预警规则日志创建失败"),
    MONITOR_RULE_ALERT_DELETE_FAILED("20029", "预警规则日志删除失败"),
    MONITOR_RULE_ADVANCE_QTY_IS_NULL("20030", "预警规则提前量不能为空"),
    MONITOR_RULE_ADVANCE_ERROR("20031", "预警规则提前量必须为正整数"),
    MONITOR_RULE_MATERIAL_ERROR("20032", "物料%s已在规则中存在"),


    IN_OUT_INCONSISTENT("30001", "库存转移，出库入库批次须一致"),
    MATERIAL_BATCH("30002", "物料批次数据不存在"),
    NO_INVENTORY("30002", "查不到库存数据"),
    MDOC_NOT_EXIST("30003", "物料凭证号不存在"),
    MDOC_OUTBOUND_REPEAT_SAMETIME("30004", "相同物料在同一逻辑仓内同一时间只能有一个出库操作"),
    MDOC_INBOUND_CANCEL_REPEAT_SAMETIME("30005", "相同物料在同一逻辑仓内同一时间只能有一个入库冲销操作"),
    TRANSFER_TO_STOCK_REPEAT_SAMETIME("30006", "相同物料在同一逻辑仓内同一时间只能有一个在途转在库操作"),
    TRANSFER_QUANTITY_TO_LARGE("30007", "转换数量不能大于已存在的在途库存量"),
    TRANSFER_TRANSIT_STOCK_TO_IN("30008","入库无法调整在途库存"),
    OUT_ERROR("30009","出库异常"),

    /**
     * Plan-specific codes (merged from domain/plan/common/enums/ResponseCodeEnum)
     * C_* series: common plan errors
     */
    PLAN_PARAMETER_VALIDATE_FAIL("C_0001", "参数校验失败"),
    PLAN_GET_LOGIN_USER_FAILED("C_0002", "获取登录用户信息失败"),
    PLAN_REMOTE_SERVICE_FAILED("C_0003", "远程服务调用异常"),
    PLAN_TENANT_ID_IS_NULL("C_0004", "租户ID不能为空"),
    PLAN_USER_INFO_IS_NULL("C_0005", "用户信息不能为空"),
    PLAN_DATA_IS_NULL("C_0006", "数据不存在"),
    PLAN_DATA_IS_ERROR("C_0007", "数据异常"),
    PLAN_NO_AUTH("C_8888", "越权操作"),
    PLAN_SYSTEM_ERROR("C_9999", "系统异常"),

    // D_* series: demand plan errors
    D_CREATE_DEMAND_PLAN_FAIL("D_CREATE_DEMAND_PLAN_FAIL_0001", "创建需求计划失败"),
    D_CREATE_DEMAND_PLAN_INVALID_DAYS("D_CREATE_DEMAND_PLAN_FAIL_0002", "计划展望期不能大于180天"),
    D_CREATE_DEMAND_PLAN_INVALID_HORIZON_DATE("D_CREATE_DEMAND_PLAN_FAIL_0003", "计划展望期开始时间不能大于结束时间"),
    D_CREATE_DEMAND_PLAN_INVALID_FIRST_DAY("D_CREATE_DEMAND_PLAN_FAIL_0004", "计划展望期开始时间非周期第一天"),
    D_CREATE_DEMAND_PLAN_INVALID_LAST_DAY("D_CREATE_DEMAND_PLAN_FAIL_0005", "计划展望期开始时间非周期第一天"),
    D_CANCEL_DEMAND_PLAN_MATERIAL_FAIL("D_CREATE_DEMAND_PLAN_FAIL_0006", "剔除物料失败"),
    D_COMMON_STATUS_NOT_OFF("D_CREATE_DEMAND_PLAN_FAIL_0007", "计划非停用状态，不可修改数据"),
    D_MODIFY_DEMAND_PLAN_MATERIAL_AMOUNT_FAIL("D_CREATE_DEMAND_PLAN_FAIL_0008", "修改物料数量失败"),
    D_UPDATE_DEMAND_PLAN_FAIL("D_CREATE_DEMAND_PLAN_FAIL_0009", "修改需求计划失败"),
    D_DEMAND_PLAN_NOT_EXIST("D_CREATE_DEMAND_PLAN_FAIL_0010", "需求计划不存在"),

    // PI_* series: plan instance / generate errors
    PI_PARAMS_NOT_EFFECTIVE_PLAN("PI_GENERATE_001", "计划方案不存在或状态停用"),
    PI_PARAMS_NOT_EFFECTIVE_PARAMETER("PI_GENERATE_002", "物料计划方案不存在"),
    PI_PARAMS_EXCEED_PLAN_RANGE("PI_GENERATE_003", "计划方案起止时间超出计算日期"),
    PI_PARAMS_EMPTY_MATERIALS("PI_GENERATE_004", "计划方案不存在有效的物料信息"),
    PI_ENTRANCE_NET_REQUIREMENT("PI_GENERATE_101", "订货策略-净需求规则不支持准入"),
    PI_ENTRANCE_INVENTORY_BALANCE("PI_GENERATE_102", "订货策略-根据目标库存差额规则不支持准入"),
    PI_ENTRANCE_MESSAGE_DURING_INTERVAL("PI_EXECUTE_103", "消息类型的计划方案未达到触发时间"),
    PI_EXECUTE_MANUAL_UNCOMPLETED("PI_EXECUTE_201", "计划方案未执行完，请稍后重试"),
    PI_REPORT_NOT_EXIST("PI_REPORT_301", "不存在的物料计划报表，请确认后重试"),

    // P_* / PMP_* series: plan material param create errors
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_MATERIAL_CODE_IS_NULL("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0001", "物料编码为空"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_LOGICAL_PLANT_NO_IS_NULL("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0002", "逻辑仓编码为空"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_LOGICAL_PLANT_NAME_IS_NULL("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0003", "逻辑仓名称为空"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_PLAN_TYPE_ERROR("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0004", "计划类型错误"),
    PMP_CREATE_FINISH_RATE_IS_NULL_WHEN_PURCHASE_TYPE("PMP_CREATE_005", "采购类型下成品率不能为空"),
    PMP_CREATE_LOSS_RATE_IS_NULL_WHEN_NO_PURCHASE_TYPE("PMP_CREATE_006", "调拨/采购类型下损耗率不能为空"),
    PMP_CREATE_TIME_FENCE_IS_NULL_WHEN_MTS13("PMP_CREATE_007", "MTS13需求响应策略下计划时区和需求时区不能为空"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_DEMAND_STRATEGY_CODE_ERROR("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0008", "策略编码为空或不在维护范围内"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_MATERIAL_CODE_IS_NOT_EXIST("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0009", "物料编码不存在"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_LOGICAL_PLANT_NO_IS_NOT_EXIST("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0010", "逻辑仓不存在"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_TRANSFER_LOGICAL_PLANT_NO_IS_NOT_EXIST("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0011", "无效调拨源头逻辑仓"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_TRANSFER_LOGICAL_PLANT_NO_IS_NOT_EMPTY("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0012", "计划类型为调拨时，调拨源头逻辑仓不能为空"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_RELATED_BOM_IS_NOT_EMPTY("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0013", "计划类型为生产时，必须关联BOM"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_TENANT_WITHOUT_LOGICAL_PLANT_NO("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0014", "当前租户下无可用逻辑仓"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_MATERIAL_PLANT_REF_ERROR("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0015", "该逻辑仓不存在该物料"),
    PMP_CREATE_TRANSFER_MATERIAL_IS_NOT_EXIST("PMP_CREATE_0016", "调拨源头仓仅可选择该物料已配置过物料计划参数的逻辑仓"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_LOGICAL_PLANT_NO_IS_SAME("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0017", "不可从当前仓调拨"),
    P_CREATE_PLAN_MATERIAL_PARAM_FAIL_TRANSFER_LOGICAL_PLANT_NO_IS_LIMIT("P_CREATE_PLAN_PARAM_MATERIAL_FAIL_0018", "该物料计划参数非调拨类型，不需填写调拨源头仓"),
    PMP_CREATE_DEMAND_TYPE_IS_NULL("PMP_CREATE_0019", "物料计划参数物料需求类型不能为空"),
    PMP_CREATE_SAFETY_STOCK_FIXED_IS_NULL("PMP_CREATE_0020", "物料计划参数安全库存设定不能为空"),
    PMP_CREATE_SAFETY_STOCK_FORMULA_IS_NULL("PMP_CREATE_0021", "物料计划参数物料安全库存公式参数不能为空"),
    PMP_CREATE_SAFETY_STOCK_RULE_IS_NULL("PMP_CREATE_0022", "物料计划参数物料安全库存计算方式不能为空"),
    PMP_CREATE_ORDER_QUANTITY_MUST_BE_POSITIVE("PMP_CREATE_0023", "订购批量必须是正整数"),
    PMP_CREATE_MIN_ORDER_QUANTITY_MUST_BE_POSITIVE("PMP_CREATE_0024", "最小订购批量必须是正整数"),

    // P_UPDATE_* / PMP_UPDATE_* series: plan material param update errors
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_PLAN_TYPE_ERROR("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0001", "计划类型错误"),
    PMP_UPDATE_FINISH_RATE_IS_NULL_WHEN_PURCHASE_TYPE("PMP_UPDATE_0002", "采购类型下成品率不能为空"),
    PMP_UPDATE_LOSS_RATE_IS_NULL_WHEN_NO_PURCHASE_TYPE("PMP_UPDATE_0003", "调拨/采购类型下损耗率不能为空"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_PRODUCE_TYPE_ERROR("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0004", "生产类型的计划 计划时区和需求时区不能为空"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_DEMAND_STRATEGY_CODE_ERROR("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0005", "策略编码为空或不在维护范围内"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_VENDOR_LEAD_TIME_MUST_BE_POSITIVE("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0006", "提前期必须是正整数"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_DEMAND_TIME_FENCE_MUST_BE_POSITIVE("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0007", "需求时区必须是正整数"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_PLANNING_TIME_FENCE_MUST_BE_POSITIVE("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0008", "需求时区必须是正整数"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_ORDER_QUANTITY_MUST_BE_POSITIVE("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0009", "订购批量必须是正整数"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_ORDER_CYCLE_TIME_MUST_BE_POSITIVE("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0010", "订购周期必须是正整数"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_SAFETY_STOCK_MUST_BE_POSITIVE("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0011", "安全库存必须是正整数"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_LOSS_RATE_FORMAT_ERROR("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0012", "损耗率格式不正确"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_FINISHED_RATE_FORMAT_ERROR("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0013", "成品率格式不正确"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_RELATED_BOM_IS_NOT_EMPTY("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0014", "计划类型为生产时，bom不可为空"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_TRANSFER_LOGICAL_PLANT_NO_IS_NOT_EMPTY("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0015", "计划类型为调拨时，调拨源头逻辑仓不能为空"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_TRANSFER_LOGICAL_PLANT_NO_IS_NOT_EXIST("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0016", "无效调拨源头逻辑仓"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_LOGICAL_PLANT_NO_IS_NOT_EXIST("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0017", "逻辑仓不存在"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_TENANT_WITHOUT_LOGICAL_PLANT_NO("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0018", "当前租户下该物料编码信息不存在"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_LOGICAL_PLANT_NO_IS_SAME("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0019", "不可从当前仓调拨"),
    P_UPDATE_PLAN_MATERIAL_PARAM_FAIL_TRANSFER_MATERIAL_IS_NOT_EXIST("P_UPDATE_PLAN_PARAM_MATERIAL_FAIL_0020", "调拨源头仓仅可选择该物料已配置过物料计划参数的逻辑仓"),
    PMP_UPDATE_DEMAND_TYPE_IS_NULL("PMP_UPDATE_0021", "物料计划参数物料需求类型不能为空"),
    PMP_UPDATE_SAFETY_STOCK_RULE_IS_NULL("PMP_UPDATE_0022", "物料计划参数物料安全库存计算方式不能为空"),
    PMP_UPDATE_SAFETY_STOCK_FIXED_IS_NULL("PMP_UPDATE_0023", "物料计划参数安全库存设定不能为空"),
    PMP_UPDATE_SAFETY_STOCK_FORMULA_IS_NULL("PMP_UPDATE_0024", "物料计划参数物料安全库存公式参数不能为空"),
    PMP_UPDATE_MIN_ORDER_QUANTITY_MUST_BE_POSITIVE("PMP_UPDATE_0025", "最小订购批量必须是正整数"),
    PMP_UPDATE_TIME_FENCE_IS_NULL_WHEN_MTS13("PMP_UPDATE_0026", "MTS13需求响应策略下计划时区和需求时区不能为空"),

    // P_SAVE_PLAN_FAIL_* series: plan save errors
    P_SAVE_PLAN_FAIL_COVER_LOGICAL_PLANT_IS_NULL("P_SAVE_PLAN_FAIL_0001", "覆盖逻辑仓不能为空"),
    P_SAVE_PLAN_FAIL_COVER_MATERIAL_TYPE_IS_NULL("P_SAVE_PLAN_FAIL_0002", "计算范围不能为空"),
    P_SAVE_PLAN_FAIL_PLAN_HORIZON_ERROR("P_SAVE_PLAN_FAIL_0003", "计划展望期不能为空并且是大于0小于或等于180天"),
    P_SAVE_PLAN_FAIL_PLAN_START_TIME_ERROR("P_SAVE_PLAN_FAIL_0004", "计划开始时间不能为空并且需要满足当前时间加一天"),
    P_SAVE_FAIL_PLAN_TYPE_ERROR("P_SAVE_PLAN_FAIL_0005", "计划类型为空或格式不正确"),
    P_SAVE_PLAN_FAIL_DEMAND_PLAN_FILE_IS_NULL("P_SAVE_PLAN_FAIL_0006", "需求文件不能为空"),
    P_SAVE_PLAN_FAIL_PLAN_CALCULATE_PARAMS_IS_NULL("P_SAVE_PLAN_FAIL_0007", "计算参数不能为空"),
    P_SAVE_PLAN_FAIL_ENABLE_LOSS_RATE_ERROR("P_SAVE_PLAN_FAIL_0011", "损耗率格式不正确"),
    P_SAVE_PLAN_FAIL_ENABLE_FINISHED_RATE_ERROR("P_SAVE_PLAN_FAIL_0012", "成品率格式不正确"),
    P_SAVE_PLAN_FAIL_ENABLE_SAFETY_STOCK_ERROR("P_SAVE_PLAN_FAIL_0013", "安全库存因素格式不正确"),
    P_SAVE_PLAN_FAIL_PLAN_DELIVERY_PARAMS_IS_NULL("P_SAVE_PLAN_FAIL_0014", "投放参数不能为空"),
    P_SAVE_PLAN_FAIL_DEMAND_PLAN_FILE_ERROR("P_SAVE_PLAN_FAIL_0016", "需求文件不存在"),
    P_SAVE_PLAN_FAIL_DEMAND_PLAN_FILE_IN_CONFLICT("P_SAVE_PLAN_FAIL_0017", "需求文件正在执行计划中"),
    P_SAVE_PLAN_FAIL_LOGICAL_PLANT_IN_CONFLICT("P_SAVE_PLAN_FAIL_0018", "逻辑仓正在执行计划中"),
    P_SAVE_PLAN_FAIL_PLAN_DESC_ERROR("P_SAVE_PLAN_FAIL_0019", "方案描述为空或者超出长度限制"),
    P_SAVE_FAIL_ORDER_CALCULATE_RULE_ERROR("P_SAVE_PLAN_FAIL_0020", "订货计算规则为空或格式不正确"),
    P_SAVE_FAIL_ORDER_PRODUCT_TYPE_ERROR("P_SAVE_PLAN_FAIL_0021", "订货量类型为空或格式不正确"),
    P_SAVE_FAIL_ORDER_RULE_NOT_BELONG_TYPE("P_SAVE_PLAN_FAIL_0022", "订货计算规则不属于计划执行类型"),
    P_SAVE_FAIL_ORDER_PRODUCT_NOT_BELONG_RULE("P_SAVE_PLAN_FAIL_0023", "订货量类型不属于订货计算规则"),

    // P_CREATE_PLAN_MATERIAL_FAIL_* series
    P_CREATE_PLAN_MATERIAL_FAIL_PLAN_IS_NOT_EXIST("P_CREATE_PLAN_MATERIAL_FAIL_0001", "计划方案不存在"),
    P_CREATE_PLAN_MATERIAL_FAIL_PLAN_STATUS_IS_ON("P_CREATE_PLAN_MATERIAL_FAIL_0002", "计划方案处于启用状态 不能修改配置"),
    P_CREATE_PLAN_MATERIAL_FAIL_ERROR_LOGICAL_PLANT("P_CREATE_PLAN_MATERIAL_FAIL_0003", "该逻辑仓不在计划范围内 不能添加"),
    P_CREATE_PLAN_MATERIAL_FAIL_MATERIAL_CODE_IS_NOT_EXIST("P_CREATE_PLAN_MATERIAL_FAIL_0004", "物料编码不存在"),
    P_CREATE_PLAN_MATERIAL_FAIL_MATERIAL_CODE_IN_EXEC("P_CREATE_PLAN_MATERIAL_FAIL_0005", "该物料正在执行计划中 不能添加"),
    P_CREATE_PLAN_MATERIAL_FAIL_MATERIAL_TYPE_ERROR("P_CREATE_PLAN_MATERIAL_FAIL_0006", "计划方案不是指定物料类型 不能添加"),

    // P_CREATE_PLAN_ORDER_FAIL_* series
    P_CREATE_PLAN_ORDER_FAIL_PLAN_IS_NOT_EXIST("P_CREATE_PLAN_ORDER_FAIL_0001", "计划不存在"),
    P_CREATE_PLAN_ORDER_FAIL_PLAN_MATERIAL_PARAM_IS_NOT_EXIST("P_CREATE_PLAN_ORDER_FAIL_0002", "物料计划参数不存在"),
    P_CREATE_PLAN_ORDER_FAIL_MATERIAL_IS_NOT_EXIST("P_CREATE_PLAN_ORDER_FAIL_0003", "物料不存在"),

    // P_ISSUE_PLAN_ORDER_FAIL_* series
    P_ISSUE_PLAN_ORDER_FAIL_ORDER_IS_NOT_EXIST("P_ISSUE_PLAN_ORDER_FAIL_0001", "计划订单不存在"),
    P_ISSUE_PLAN_ORDER_FAIL_ISSUE_GREATER_THAN_PLAN("P_ISSUE_PLAN_ORDER_FAIL_0002", "下发订单量大于确认订单量"),

    // P_CHANGE_PLAN_STATUS_FAIL_* / P_CHANGE_PLAN_FAIL_* series
    P_CHANGE_PLAN_STATUS_FAIL_DEMAND_FILE_IS_NOT_EXIST("P_CHANGE_PLAN_STATUS_FAIL_0001", "计划中需求计划文件不存在"),
    P_CHANGE_PLAN_FAIL_LOGICAL_PLANT_IN_CONFLICT("P_CHANGE_PLAN_FAIL_0002", "指定物料存在计划中的逻辑仓不存在"),
    P_CHANGE_PLAN_STATUS_FAIL_PLAN_MATERIAL_IS_NULL("P_CHANGE_PLAN_FAIL_0003", "物料清单为空 请导入"),

    // P_DELETE_PLAN_MATERIAL_FAIL_* series
    P_DELETE_PLAN_MATERIAL_FAIL_NOT_EXIST("P_DELETE_PLAN_MATERIAL_FAIL_0001", "该物料清单不存在无法删除"),

    // P_CONFIRM_PLAN_ORDER_FAIL_* / P_UPDATE_PLAN_ORDER_FAIL_* series
    P_CONFIRM_PLAN_ORDER_FAIL_PLAN_IS_NOT_EXIST("P_CONFIRM_PLAN_ORDER_FAIL_0001", "计划不存在"),
    P_UPDATE_PLAN_ORDER_FAIL_PLAN_IS_NOT_EXIST("P_UPDATE_PLAN_ORDER_FAIL_0001", "计划不存在"),

    // BOM_CASE_* series
    BOM_CASE_CONFIGURATION_PARENT_IS_EXIST("BOM_CASE_CONFIGURATION_FAIL_0001", "{0}编码{1}已存在BOM中，请重新输入。"),
    BOM_CASE_CONFIGURATION_MATERIAL_IS_NULL("BOM_CASE_CONFIGURATION_FAIL_0002", "该逻辑仓下没有物料信息"),
    BOM_CASE_CONFIGURATION_MATERIAL_IS_NOT_IN_PLANT("BOM_CASE_CONFIGURATION_FAIL_0003", "物料编码 {0} 不在 {1} 逻辑仓下，请重新输入。"),
    BOM_CASE_CONFIGURATION_MATERIAL_CODE_REPEAT("BOM_CASE_CONFIGURATION_FAIL_0004", "物料编码 {0} 不可重复，请重新输入。"),
    BOM_CASE_CONFIGURATION_MATERIAL_CODE_CYCLE("BOM_CASE_CONFIGURATION_FAIL_0005", "物料编码 {0} 不可作为 {1} 的子件。"),
    BOM_CASE_CHANGE_STATUS_IS_USING_IN_PLAN("BOM_CASE_CHANGE_STATUS_FAIL_0001", "请先停用该BOM在使用的计划方案： {0} "),
    ;

    ResponseCodeEnum(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    private String code;

    private String desc;

    public static ResponseCodeEnum getByCode(String code) {
        for (ResponseCodeEnum e : ResponseCodeEnum.values()) {
            if (e.getCode().equals(code)) {
                return e;
            }
        }
        return null;
    }


    public String getCode() {
        return code;
    }

    public String getDesc() {
        return desc;
    }
}
